name: sara_sfc
channels:
  - defaults
dependencies:
  - backcall=0.1.0=py37_0
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - colorama=0.4.1=py37_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.4.0=py37_0
  - jupyterlab=0.35.4=py37hf63ae98_0
  - jupyterlab_server=0.2.0=py37_0
  - libpng=1.6.37=h2a8f88b_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - notebook=5.7.8=py37_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - pickleshare=0.7.5=py37_0
  - pip=19.0.3=py37_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - pygments=2.4.2=py_0
  - python=3.7.3=h8c8aaf0_0
  - python-dateutil=2.8.0=py37_0
  - qtconsole=4.3.1=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.8.0=py37_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.1=py37_0
  - pip:
    - asn1crypto==0.24.0
    - attrs==18.2.0
    - cffi==1.12.2
    - chardet==3.0.4
    - cryptography==2.6.1
    - cvxopt==1.2.3
    - cycler==0.10.0
    - dlx==1.0.4
    - docloud==1.0.375
    - docplex==2.9.141
    - fastdtw==0.3.2
    - idna==2.8
    - inflection==0.3.1
    - intel-openmp==2019.0
    - jsonschema==2.6.0
    - kiwisolver==1.0.1
    - marshmallow==2.19.2
    - marshmallow-polyfield==3.2
    - matplotlib==3.0.3
    - mkl==2019.0
    - more-itertools==5.0.0
    - mpmath==1.1.0
    - ndg-httpsclient==0.5.1
    - networkx==2.2
    - ntlm-auth==1.2.0
    - numpy==1.16.2
    - pandas==0.24.2
    - pdflatex==0.1.3
    - pillow==6.0.0
    - ply==3.11
    - psutil==5.6.1
    - pyasn1==0.4.5
    - pycparser==2.19
    - pylatexenc==1.5
    - pyopenssl==19.0.0
    - pyparsing==2.3.1
    - pytz==2019.1
    - qiskit==0.8.0
    - qiskit-aer==0.1.1
    - qiskit-aqua==0.5.2
    - qiskit-ignis==0.1.0
    - qiskit-terra==0.8.2
    - quandl==3.4.8
    - requests==2.21.0
    - requests-ntlm==1.1.0
    - scikit-learn==0.20.0
    - scipy==1.2.1
    - six==1.12.0
    - sympy==1.3
    - urllib3==1.24.1


